### ISSUE TITLE
Duplicate text and formatting issues when using formatted instances of the same word on one line.

### ISSUE THREAD

**Issue by robotmonkey** [kadikraman/draftjs-md-converter#14]
Hi @kadikraman, we're noticing a bug where when you use multiple (at least 2) instances of the same word on a single line, and if one of those instances is formatted using bold, italics, or bold & italics, you will see duplicatation of text and some formatting issues - https://cl.ly/iOSO. 

To reproduce this: 
- Type in the following into an editor: `First bold is fine, second bold will cause issues.` (Make one of the bold instances **BOLD**
- This should result in the following output: `First bold is fine, second bold is fine, second **bold will cause issues.`

Please let me know if I can follow up with more details. 
Thanks.

**Comment by bradbirnbaum** [comment]
@robotmonkey I'm bumping into this as well.   I have isolated it to the `fixWhitespacesInsideStyle` function at this line

https://github.com/kadikraman/draftjs-md-converter/blob/master/src/draftjsToMd.js#L86

Essentially `text.indexOf(bodyT)` is finding the first instance of the string but the assumption that its the first occurence is incorrect.   Would love to see a fix

**Comment by kadikraman** [comment]
Hi @robotmonkey - which version of Draft.js are you using?

**Comment by rickhanlonii** [comment]
Fixed on https://github.com/kadikraman/draftjs-md-converter/issues/15

**Comment by kadikraman** [comment]
Thank you @rickhanlonii I've published the change, the new version is `v0.1.1`.
