### ISSUE TITLE
Block quote conversion failing

### ISSUE THREAD

**Issue by El-Gregory** [kadikraman/draftjs-md-converter#19]
@kadikraman 
My block quotes dont seem to be being translated. 

Here is my editor state:

```
{"entityMap":{},"blocks":[{"key":"dh94v","text":"Here is a block quote.","type":"blockquote","depth":0,"inlineStyleRanges":[],"entityRanges":[],"data":{}}]}
```

Here is the draftToMD output:
```
Here is a block quote.
```

whereas this is the expected result:
```
> Here is a block quote.
```

I added block quote to the dictionary to no avail.
```
const myMdDict = {
  EMPHASIS: '*',
  BOLD: '**',
  STRIKETHROUGH: '~~',
  UNDERLINE: '__',
  CODE: '```',
  BLOCKQUOTE: '>'
};
const newMarkdown = draftjsToMd(editorState, myMdDict);
```

I'm using the react-draft-wysiwyg editor plugin to create the block quote.

**Comment by kadikraman** [comment]
Hey @El-Gregory thanks for pointing this out 😊
Try [0.1.3](https://www.npmjs.com/package/draftjs-md-converter) - that should fix it.
