### ISSUE TITLE
Bold styling is removing spaces

### ISSUE THREAD

**Issue by zackary** [kadikraman/draftjs-md-converter#23]
I ran into an issue when the following combination was entered into the draftJS editor and then converted to markdown using the draftjsToMd function

Draft JS
**A** [b]
**C** [d]
**Want more**

Markdown output
__A__ [b]
__C __[d]
__Wantmore__

DraftJS object
![screen shot 2017-07-19 at 3 20 41 pm](https://user-images.githubusercontent.com/1180393/28351843-e16c371c-6c95-11e7-9ad4-af9c881e25bf.png)

**Comment by kadikraman** [comment]
Hi @zackary - thanks for the incredibly detailed bug report, it's been super helpful. I've written a failing test based on it: https://github.com/kadikraman/draftjs-md-converter/pull/24

I'm pretty sure the culprit it [this `fixWhitespacesInsideStyle` function](https://github.com/kadikraman/draftjs-md-converter/blob/master/src/draftjsToMd.js#L72) which was introduced to fix a different whitespace issue. I'm looking into fixing this.

**Comment by zackary** [comment]
No problem @kadikraman. When do you think a fix will be completed by?

**Comment by kadikraman** [comment]
Ohh, I think I got it. Please confirm it works for you @zackary 
Should be fixed in `v0.1.5`

**Comment by kadikraman** [comment]
I'm closing this issue. Please reopen it if the problem persists.

**Comment by zackary** [comment]
Issue's resolved. Thanks!
