### ISSUE TITLE
Tag the last fixes

### ISSUE THREAD

**Issue by AdilHoumadi** [kadikraman/draftjs-md-converter#38]
Hello @kadikraman,

Can you tag the last commit of the master branch ?  in order to have the last fix concerning ```@textlint/markdown-to-ast```.

Thanks.

**Comment by kadikraman** [comment]
Sorry, I forgot I hadn't released the latest. I was waiting for a confirmation that an issue has been fixed.

Released now as [v1.1.0](https://github.com/kadikraman/draftjs-md-converter/releases/tag/v1.1.0) 🎉
