### ISSUE TITLE
Inline styles sometimes eating spaces

### ISSUE THREAD

**Issue by tjkind** [kadikraman/draftjs-md-converter#39]
I'm using this library along with `react-draft-wysiwyg` and I've found a scenario where the markdown will be missing a space after conversion.
Pre conversion text: __This__ is not *fine*
Post conversion text: __This__ is not*fine*
Doesn't lose any spaces: *This* is __fine__
Conversion code:  ```draftjsToMd(convertToRaw(body.getCurrentContent()))```
RawDraftContentState:
![screen shot 2018-07-04 at 3 47 17 pm](https://user-images.githubusercontent.com/34299475/42295700-f03091a6-7fa1-11e8-9d7e-db3b439ef8bb.png)

I think I fixed it locally by adding ```totalOffset += endingStyle.symbol.length;```  after adding the closing symbol but I'm not confident enough in this fix to open a pull request

**Comment by kadikraman** [comment]
Thanks for the detail! I think it's fine to add it, because it doesn't break any of the existing tests and I was able to add a failing test based on your example 💯 

Released as a patch [v1.1.1](https://github.com/kadikraman/draftjs-md-converter/releases/tag/v1.1.1) 🎉
