### ISSUE TITLE
Identifier '_toConsumableArray' has already been declared

### ISSUE THREAD

**Issue by in-html** [kadikraman/draftjs-md-converter#55]
I use React, Parcel and draftjs-md-converter. When i run the command "yarn start" I get an error:
`Identifier '_toConsumableArray' has already been declared`.
It seems the function is declared 2 times.

**Comment by kadikraman** [comment]
Hi @in-html 👋 - I've raised a PR with a fix. If you get a moment, I'd really appreciate if you could check if it works for you. The instructions on how to verify are in the PR description - cheers!
