### ISSUE TITLE
How to use this in the browser

### ISSUE THREAD

**Issue by vabatta** [kadikraman/draftjs-md-converter#73]
The library doesn't work in the browser as it uses `path` and `process`, but I don't see the reason for such as it manipulates strings (why the need of `process` or `path`).
 
When I added this to the bundle, webpack failed with 
`Module not found: Error: Can't resolve 'path' in <bundle>`

**Comment by chrisrobbins** [comment]
@vabatta Did you find a solution for this?

**Comment by vabatta** [comment]
Nope, we ended up by using a custom made library and some quirks workaround.
